[package]
name = "crdt"
version = "0.1.0"
authors = ["mhallin <mhallin@gmail.com>"]

[dependencies]
rustc-serialize = "*"
uuid = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]
